apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: app-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-storage
  volumes:
    - name: html-storage
      persistentVolumeClaim:
        claimName: my-pvc
